"""Human-readable Markdown report renderer."""

from __future__ import annotations

from papercheck.models import DiagnosticReport, Finding, LayerResult


_SEVERITY_ICONS = {
    "critical": "!!",
    "error": "!",
    "warning": "?",
    "info": "-",
}

_SIGNAL_ICONS = {
    "pass": "PASS",
    "warn": "WARN",
    "fail": "FAIL",
}


def render_markdown(report: DiagnosticReport) -> str:
    """Render a DiagnosticReport as a Markdown document."""
    lines: list[str] = []

    # Header
    lines.append(f"# Paper Verification Report\n")
    lines.append(f"**Title**: {report.title or '(unknown)'}")
    if report.authors:
        lines.append(f"**Authors**: {', '.join(report.authors)}")
    lines.append(
        f"**Composite Score**: {report.composite_score:.2f} / 1.00 "
        f"({_SIGNAL_ICONS.get(report.composite_signal, report.composite_signal)})"
    )
    lines.append("")

    # Summary table
    lines.append("## Summary\n")
    lines.append("| Layer | Score | Signal | Findings |")
    lines.append("|-------|-------|--------|----------|")
    for lr in report.layer_results:
        if lr.skipped:
            lines.append(
                f"| {lr.layer}. {lr.layer_name} | — | SKIPPED | {lr.skip_reason or ''} |"
            )
        else:
            finding_summary = _summarize_findings(lr.findings)
            lines.append(
                f"| {lr.layer}. {lr.layer_name} | {lr.score:.2f} | "
                f"{_SIGNAL_ICONS.get(lr.signal, lr.signal)} | {finding_summary} |"
            )
    lines.append("")

    # Per-layer details
    for lr in report.layer_results:
        lines.append(f"## Layer {lr.layer}: {lr.layer_name} ({lr.score:.2f})\n")
        if lr.skipped:
            lines.append(f"*Skipped: {lr.skip_reason}*\n")
            continue
        if not lr.findings:
            lines.append("No findings.\n")
            continue
        lines.append("### Findings\n")
        for f in sorted(lr.findings, key=lambda x: _severity_rank(x.severity)):
            icon = _SEVERITY_ICONS.get(f.severity, "-")
            loc = f" [{f.location}]" if f.location else ""
            lines.append(f"- **{icon} {f.severity.upper()}**{loc}: {f.message}")
            if f.evidence:
                lines.append(f"  - Evidence: {f.evidence}")
            if f.suggestion:
                lines.append(f"  - Suggestion: {f.suggestion}")
        lines.append("")

    # Footer
    lines.append("---\n")
    lines.append(
        f"*Generated by papercheck v{report.pipeline_version} | "
        f"{report.total_execution_time_seconds:.1f}s | "
        f"${report.total_llm_cost_usd:.2f} LLM cost | "
        f"{report.timestamp}*"
    )

    return "\n".join(lines)


def _summarize_findings(findings: list[Finding]) -> str:
    """Count findings by severity."""
    counts: dict[str, int] = {}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    parts = []
    for sev in ("critical", "error", "warning", "info"):
        if sev in counts:
            parts.append(f"{counts[sev]} {sev}")
    return ", ".join(parts) if parts else "none"


def _severity_rank(severity: str) -> int:
    return {"critical": 0, "error": 1, "warning": 2, "info": 3}.get(severity, 4)
